### ISSUE TITLE
Tor Browser Launcher fails on Kubuntu 23.04 

### ISSUE THREAD

**Issue by fractal815** [torproject/torbrowser-launcher#708] opened 2023-09-25 18:56 UTC
Tor Browser Launcher fails on Kubuntu 23.04 .     Removed and reinstalled TBL from Discover to no avail.    
![Screenshot_20230925_145012](https://github.com/micahflee/torbrowser-launcher/assets/16502902/25d04957-854e-4581-8e5f-90dba52e80b7)

**Comment by boklm** [comment] 2023-10-03 12:05
This should be fixed now. This was caused by https://gitlab.torproject.org/tpo/applications/tor-browser-build/-/issues/40957.

**Closed** 2023-10-03 12:43 UTC
